# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box"

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :openstack do |os|
    os.username     = "admin"          # e.g. "#{ENV['OS_USERNAME']}"
    os.api_key      = "devstack"           # e.g. "#{ENV['OS_PASSWORD']}"
    os.flavor       = "m1.tiny"                # Regex or String
    os.image        = "cirros-0.3.2-x86_64-uec-ramdisk"                 # Regex or String
    os.endpoint     = "http://10.0.2.15:5000/v2.0/tokens"      # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.ssh_username = "root"           # login for the VM
    os.tenant = "admin"
  end
end
