# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "aws-east"
    aws.security_groups =  	["test"]
    aws.ami = "ami-7747d01e"
    aws.region = "us-east-1"
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/aws-east.pem"
  end
end
