# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "aws-east"
    aws.security_groups =  	["test"]
    # RHEL 6.5
    aws.ami = "ami-b06a98d8"
    aws.region = "us-east-1"
    aws.user_data = "#!/bin/bash\necho 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/999-vagrant-cloud-init-requiretty && chmod 440 /etc/sudoers.d/999-vagrant-cloud-init-requiretty"    

    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "~/.ssh/aws-east.pem"
  end
end
