# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", path: "devstack-install.sh"
  config.vm.network "private_network", ip: "10.11.12.2"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.box = "chef/centos-6.5"
  config.vm.synced_folder "./", "/vagrant"
  config.vm.host_name =  "devstack"
  # dashboard
  config.vm.network "forwarded_port", guest: 80,   host: 8888
  # keystone
  config.vm.network "forwarded_port", guest: 5000, host: 8889

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end
end
