# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box"

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = "~/.ssh/os1.pem"
  config.vm.provider :openstack do |os|
    os.username     = ENV['OS_USERNAME']
    os.api_key      = ENV['OS_PASSWORD']
    os.flavor       = "m1.medium"                # Regex or String
    os.image        = /CentOS/                 # Regex or String
    os.ssh_username = "centos"           # login for the VM
    os.tenant = "ENG Big Data"
    os.endpoint     = "http://control.os1.phx2.redhat.com:5000/v2.0/tokens"      # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.security_groups    = 'default'
    os.server_name = "my-machine"
    os.keypair_name = "hchen"
    os.floating_ip = "auto"
  end
end
